http:
  listener:
    host: "0.0.0.0"
    port: "8081"
    path: "/jmsPubSub"

https:
  requester:
    host: "dummy.restapiexample.com"
    port: "80"
    path: "/api/v1/employees"
jms:
  username: "admin"
  pswd: "admin"